# Generated by Django 3.2.21 on 2024-03-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_profile_second_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='website/images')),
            ],
        ),
    ]
