# Generated by Django 3.2.21 on 2024-03-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='strength',
            name='Advanced',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='strength',
            name='Beginner',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='strength',
            name='Elite',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='strength',
            name='Intermediate',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='strength',
            name='Novice',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
